INC= /Users/galacticPast/Documents/raylib/src
LIB= /Users/galacticPast/Documents/raylib/src
Asteroids:
		gcc -framework CoreVideo -framework IOKit -framework Cocoa -framework GLUT -framework OpenGL  -L$(LIB) -lraylib -I$(INC)  Asteroids.c -o ../build/Asteroids -g 
